name: Run Jupyter Notebooks

on:
  push:
    paths:
      - '**.ipynb'
      - '.github/workflows/run-notebooks.yml'
  pull_request:
    paths:
      - '**.ipynb'
      - '.github/workflows/run-notebooks.yml'

jobs:
  test-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Get all history so tj-actions/changed-files can diff against main
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up uv and install dependencies
        run: |
          pip install --upgrade pip
          pip install uv
          uv sync

      - name: Run all notebooks
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          set -e
          for nb in $(find . -name "*.ipynb"); do
            echo "Running $nb"
            uv run jupyter nbconvert --to notebook --execute --inplace "$nb"
          done
